version: '3.8'

services:
  postgres:
    container_name: mechanic-postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    restart: always

  pgadmin:
    container_name: mechanic-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'flank.silva.0@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'docker@123'
    ports:
      - '5050:80'
    restart: always
